name: uix_todomvc
version: 0.0.1
author: Boris Kaul <localvoid@gmail.com>
description: TodoMVC Example for uix library.
environment:
  sdk: '>=1.9.1'
dependencies:
  browser: any
  route_hierarchical: any
  uix: '^0.7.0'
  uix_forms:
    git: git://github.com/localvoid/uix_forms.git
dependency_overrides:
  uix:
    git: git://github.com/localvoid/uix.git
