name: uix_todomvc
version: 0.0.1
author: Boris Kaul <localvoid@gmail.com>
description: TodoMVC Example for uix library.
environment:
  sdk: '>=1.9.1'
dependencies:
  browser: any
  route_hierarchical: any
  uix:
    git: git://github.com/localvoid/uix.git
